### ISSUE TITLE
where to start if i want to create a fmv game based on this engine

### ISSUE THREAD

**Issue by abasgames** [Rinnegatamante/OpenFMV#3]

**Comment by Rinnegatamante** [comment]
Assuming you already have your videos shot and related subtitles files;
You'll have to add a new game target in the makefile ( https://github.com/Rinnegatamante/OpenFMV/blob/master/Makefile#L32-L38 ) for the game and then mimic late_shift.c but to suit your game. Looking at that file should give an idea of what's the general workflow of the engine but, in case you need any more details, just ask.
