### ISSUE TITLE
Missing Polish subtitles in Late Shift

### ISSUE THREAD

**Issue by szczuru** [Rinnegatamante/OpenFMV#4]
Hi, i've managed to convert PC version of Late Shift to Vita and polish subtitles are missing i can choose from en/fr/es/de/it/pt-br/ru/dk/tr/ua nad few others but PL is missing (files for it are present in data/Late Shift/Subtitles dir). Any planned fix?

Regards

**Comment by Rinnegatamante** [comment]
I think I didn't include polish support due to the fact polish characters would require a font having support for extra characters.

**Comment by szczuru** [comment]
Yes, polish have few non ascii characters. Is it possible to add this language? Maybe with dedicated/separate font?

**Comment by szczuru** [comment]
Hi, sorry for bumping issue but i've tried to replace english subs with polish (just renamed pl.zip to en.zip) and it works :D at lest in game (menus are still in english). Font in subtitles is displayed correctly BUT when scene is played with "choose" option these options are displayed still in english. Maybe this will be simpler to fix than adding full polish support?

**Comment by Rinnegatamante** [comment]
The choices come from https://github.com/Rinnegatamante/OpenFMV/blob/master/data/Late%20Shift/lang/pl.str . Check if those work fine (by replacing it with eng ones). If everything works fine, I guess it's safe to integrate polish language.

**Comment by szczuru** [comment]
It works :) After renaming that file choices are displayed in polish with correct font. Played for like 30minutes and everything seems to be displaying fine. Even menu is in polish except one line in settings: "Audio driver" which in polish it should be "Sterownik audio". Thanks Rinnegatamante!

**Comment by szczuru** [comment]
L
